import type { Lang } from "./content";

export const HOME_PREMIUM = {
  fr: {
    hero: {
      titleBefore: "L’IA ne doit pas être ",
      titleAccent: "un outil de plus.",
      titleAfter: " Elle doit transformer le fonctionnement de votre entreprise.",
      sub: "De la stratégie à l’exécution, Remparia fait de l’IA un système d’exploitation gouverné pour votre activité.",
      ctaPrimary: "Construire votre modèle d’exploitation IA",
      ctaSecondary: "Voir Remparia en action",
      badges: [
        "Prêt souveraineté",
        "Agnostique modèles",
        "Contrôle humain",
        "Gouvernance d’entreprise",
      ],
    },
    problem: {
      eyebrow: "02 / LE CONSTAT",
      titleBefore: "Tout le monde expérimente l’IA. ",
      titleAccent: "Peu d’entreprises l’exploitent vraiment.",
      sideLead: "Le défi",
      sideRest: "n’est plus d’accéder à l’IA. C’est d’en faire une ",
      sideAccent: "capacité opérationnelle.",
      today: "AUJOURD’HUI",
      withUs: "AVEC REMPARIA",
      rows: [
        { today: "Chatbots", withUs: "Travailleurs IA" },
        { today: "PoC isolés", withUs: "Workflows connectés" },
        { today: "10 outils différents", withUs: "Une couche d’exploitation" },
        { today: "Shadow AI", withUs: "IA gouvernée" },
        { today: "ROI flou", withUs: "Résultats mesurés" },
      ],
    },
    model: {
      eyebrow: "03 / NOTRE MODÈLE",
      title: "Notre méthode. Votre modèle d’exploitation IA.",
      steps: [
        {
          n: "01",
          tag: "SIGNAL",
          icon: "signal",
          title: "Trouver la valeur.",
          desc: "Découvrir, prioriser et quantifier où l’IA peut transformer vos opérations.",
          items: ["Découvrir", "Scorer", "Prioriser", "ROI"],
        },
        {
          n: "02",
          tag: "STUDIO",
          icon: "studio",
          title: "Construire la force de travail.",
          desc: "Concevoir des agents IA spécialisés et des workflows multi-agents autour de votre métier.",
          items: ["Agents", "Compétences", "Workflows", "Outils"],
        },
        {
          n: "03",
          tag: "OS",
          icon: "os",
          title: "Faire tourner le système.",
          desc: "Un plan de contrôle unique pour orchestrer agents, modèles, outils et données enterprise.",
          items: ["Modèles", "Agents", "Données", "Connecteurs"],
        },
        {
          n: "04",
          tag: "GOUVERNANCE",
          icon: "governance",
          title: "Garder le contrôle.",
          desc: "Observer chaque action. Contrôler les permissions. Auditer les décisions. Gouverner l’IA à l’échelle.",
          items: ["Identité", "Politiques", "Audit", "Observabilité"],
        },
      ],
    },
    org: {
      eyebrow: "04 / EN ACTION",
      titleBefore: "Voir une organisation IA ",
      titleAccent: "au travail.",
      body: "Une mission entre, l’orchestrateur délègue, les agents exécutent, l’humain valide — le tout journalisé dans Remparia OS.",
      cta: "Lancer la démo interactive",
      logTitle: "Activité",
      logs: [
        { icon: "mission", title: "Nouvelle mission reçue", time: "10:23:54" },
        { icon: "sales", title: "Agent Ventes démarré", time: "10:32:13" },
        { icon: "document", title: "Agent Document appelé", time: "10:52:21" },
        { icon: "crm", title: "Outil CRM utilisé", time: "10:57:27" },
        { icon: "human", title: "Validation humaine", time: "11:03:02" },
        { icon: "done", title: "Mission terminée", time: "11:06:14" },
      ],
      saved: "14 min économisées",
      human: { title: "HUMAIN", desc: "Approuve / Valide" },
      orchestrator: { title: "ORCHESTRATEUR", desc: "Planifie et délègue" },
      agents: [
        { icon: "salesai", title: "IA VENTES", desc: "Qualifier & engager" },
        { icon: "docai", title: "IA DOCS", desc: "Lire & préparer" },
        { icon: "finance", title: "IA FINANCE", desc: "Analyser & contrôler" },
      ],
      os: "REMPARIA OS",
      tools: [
        { icon: "crm", label: "CRM" },
        { icon: "erp", label: "ERP" },
        { icon: "email", label: "E-mail" },
        { icon: "docs", label: "Docs" },
        { icon: "apis", label: "APIs" },
      ],
    },
    workforce: {
      eyebrow: "05 / FORCE DE TRAVAIL IA",
      titleBefore: "N’ajoutez pas un chatbot. ",
      titleAccent: "Construisez une force de travail IA.",
      body: "Les agents ne travaillent pas seuls. Ils collaborent dans des workflows gouvernés par Remparia OS.",
      agents: [
        {
          tag: "RESEARCH",
          title: "Agent Recherche",
          desc: "Recherche, synthèse et sourcing sous règles métier.",
        },
        {
          tag: "SALES",
          title: "Agent Ventes",
          desc: "Qualification, suivi et préparation commerciale.",
        },
        {
          tag: "DOCUMENT",
          title: "Agent Document",
          desc: "Collecte, contrôle et production documentaire.",
        },
        {
          tag: "OPS",
          title: "Agent Opérations",
          desc: "Processus récurrents, escalades et reporting.",
        },
        {
          tag: "FINANCE",
          title: "Agent Finance",
          desc: "Contrôles, rapprochements et préparation analytique.",
        },
        {
          tag: "CUSTOM",
          title: "Agent sur mesure",
          desc: "Construisez votre propre agent IA.",
          href: "/studio",
        },
      ],
    },
    sovereignty: {
      eyebrow: "06 / SOUVERAINETÉ",
      titleBefore: "Votre IA. Votre infrastructure. ",
      titleAccent: "Vos règles.",
      os: "REMPARIA OS",
      osTagline: "ORCHESTRER. GOUVERNER. SCALER.",
      modes: [
        {
          id: "cloud",
          title: "Cloud Remparia",
          subtitle: "Géré par Remparia",
          badge: "Le plus rapide",
          badgeIcon: "zap",
          attrs: [
            { label: "Déploiement", value: "Géré", icon: "cloud" },
            { label: "Résidence des données", value: "Configurable", icon: "database" },
            { label: "Contrôle infra", value: "Remparia", icon: "building" },
          ],
          modelsLabel: "Modèles",
          models: [
            { label: "Mistral", icon: "mistral" },
            { label: "Llama", icon: "llama" },
            { label: "OpenAI", icon: "openai" },
            { label: "Anthropic", icon: "anthropic" },
          ],
          base: [
            { label: "Données entreprise", icon: "database" },
            { label: "Agents IA", icon: "agents" },
          ],
          tools: [
            { label: "CRM", icon: "crm" },
            { label: "ERP", icon: "erp" },
            { label: "E-mail", icon: "email" },
            { label: "Docs", icon: "docs" },
            { label: "APIs", icon: "apis" },
          ],
          features: [
            "Mise en production en jours",
            "Modèles publics au choix",
            "Exploitation 100 % gérée",
          ],
          tagline: "Le chemin le plus rapide vers la production",
          taglineIcon: "zap",
        },
        {
          id: "sovereign",
          title: "Cloud souverain",
          subtitle: "Infrastructure européenne",
          badge: "EU / France",
          badgeIcon: "shield",
          boundary: "Périmètre souverain EU / France",
          attrs: [
            { label: "Déploiement", value: "Environnement souverain", icon: "globe" },
            { label: "Résidence des données", value: "EU / France", icon: "database" },
            { label: "Contrôle infra", value: "Dédié", icon: "server" },
          ],
          modelsLabel: "Modèles",
          models: [
            { label: "Mistral", icon: "mistral" },
            { label: "Llama", icon: "llama" },
            { label: "LLM privé", icon: "private" },
          ],
          base: [
            { label: "Agents IA", icon: "agents" },
            { label: "Données entreprise", icon: "database" },
          ],
          tools: [
            { label: "CRM", icon: "crm" },
            { label: "ERP", icon: "erp" },
            { label: "E-mail", icon: "email" },
            { label: "Docs", icon: "docs" },
            { label: "APIs", icon: "apis" },
          ],
          features: [
            "Résidence des données",
            "Réseau isolé",
            "Chiffrement au repos et en transit",
            "Journaux d’audit et supervision",
            "Conformité souveraine (RGPD, NIS2, DORA…)",
          ],
          tagline: "Infrastructure européenne. Contrôle entreprise.",
          taglineIcon: "shield",
        },
        {
          id: "onprem",
          title: "On-premise",
          subtitle: "Votre infrastructure. Vos règles.",
          badge: "Air-gap",
          badgeIcon: "lock",
          boundary: "Périmètre client — aucune donnée ne sort",
          attrs: [
            { label: "Déploiement", value: "Infra client", icon: "server" },
            { label: "Résidence des données", value: "Environnement client", icon: "database" },
            { label: "Contrôle infra", value: "Client", icon: "key" },
          ],
          modelsLabel: "Modèles privés",
          models: [
            { label: "Llama", icon: "llama" },
            { label: "Mistral", icon: "mistral" },
            { label: "LLM custom", icon: "private" },
          ],
          base: [
            { label: "Agents IA", icon: "agents" },
            { label: "Données entreprise", icon: "database" },
            { label: "Outils", icon: "tools" },
          ],
          tools: [
            { label: "ERP", icon: "erp" },
            { label: "CRM", icon: "crm" },
            { label: "GED", icon: "folder" },
            { label: "Bases de données", icon: "database" },
            { label: "APIs", icon: "apis" },
          ],
          features: [
            "Réseau privé",
            "Aucune donnée ne quitte votre environnement",
            "Clés gérées par le client",
            "Audit et observabilité",
            "Prêt air-gap*",
          ],
          tagline: "Contrôle maximum. Zéro compromis.",
          taglineIcon: "lock",
        },
      ],
      compare: {
        columns: ["Cloud Remparia", "Cloud souverain", "On-premise"],
        rows: [
          {
            label: "Vitesse de déploiement",
            values: ["Rapide", "Moyenne", "Plus longue"],
            icons: ["zap", "clock", "hourglass"],
          },
          {
            label: "Pilotage",
            values: [
              "Géré Remparia",
              "Remparia + partenaire / client",
              "Client (avec support Remparia)",
            ],
          },
          {
            label: "Flexibilité",
            values: ["Élevée", "Très élevée", "Maximum"],
          },
          {
            label: "Idéal pour",
            values: [
              "Démarrage rapide, agilité",
              "Industries régulées, souveraineté",
              "Environnements sensibles, contrôle total",
            ],
          },
        ],
      },
    },
    industries: {
      eyebrow: "07 / SOLUTIONS MÉTIERS",
      titleBefore: "Conçu pour ",
      titleAccent: "votre industrie.",
      titleAfter: " Pas à partir de zéro.",
      body: "Choisissez votre industrie. Nous déployons votre force de travail IA.",
      orchestrator: "ORCHESTRATEUR",
      osTitle: "REMPARIA OS",
      osTagline: "GOUVERNER. ORCHESTRER. SCALER.",
      tabs: [
        {
          id: "real-estate",
          label: "IMMOBILIER",
          title: "Force de travail IA — Immobilier",
          cta: "Explorer le pack Immobilier",
          agents: [
            {
              icon: "lead",
              name: "Agent qualification de leads",
              desc: "Qualifiez et scorez les leads automatiquement depuis plusieurs sources.",
            },
            {
              icon: "property",
              name: "Agent matching de biens",
              desc: "Associez les bons biens aux bons prospects.",
            },
            {
              icon: "document",
              name: "Agent Document",
              desc: "Extrayez, classez et gérez les documents immobiliers.",
            },
            {
              icon: "support",
              name: "Agent support locataires",
              desc: "Répondez aux locataires et résolvez les demandes instantanément.",
            },
            {
              icon: "reporting",
              name: "Agent reporting",
              desc: "Générez des insights et rapports sur la performance et l’occupation.",
            },
            {
              icon: "ops",
              name: "Agent opérations",
              desc: "Automatisez les tâches opérationnelles et gagnez en efficacité.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "ERP" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "PROPERTY APIs" },
          ],
        },
        {
          id: "legal",
          label: "JURIDIQUE",
          title: "Force de travail IA — Juridique",
          cta: "Explorer le pack Juridique",
          agents: [
            {
              icon: "document",
              name: "Agent revue documentaire",
              desc: "Analysez et synthétisez les dossiers juridiques à grande échelle.",
            },
            {
              icon: "ops",
              name: "Agent préparation de dossier",
              desc: "Préparez les éléments de dossier et les échéances.",
            },
            {
              icon: "reporting",
              name: "Agent contrôle de conformité",
              desc: "Contrôlez la conformité et signalez les écarts.",
            },
            {
              icon: "support",
              name: "Agent intake client",
              desc: "Qualifiez les demandes clients et orientez les dossiers.",
            },
            {
              icon: "lead",
              name: "Agent recherche",
              desc: "Recherchez jurisprudence et sources sous règles métier.",
            },
            {
              icon: "property",
              name: "Agent rédaction de contrats",
              desc: "Préparez des projets de contrats et clauses types.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "DMS" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "LEGAL APIs" },
          ],
        },
        {
          id: "finance",
          label: "SERVICES FINANCIERS",
          title: "Force de travail IA — Services financiers",
          cta: "Explorer le pack Finance",
          agents: [
            {
              icon: "lead",
              name: "Agent assistance KYC",
              desc: "Accélérez le KYC et la collecte documentaire.",
            },
            {
              icon: "reporting",
              name: "Agent reporting",
              desc: "Produisez des reportings réglementaires et analytiques.",
            },
            {
              icon: "ops",
              name: "Agent préparation risque",
              desc: "Préparez les contrôles risque et les dossiers d’alerte.",
            },
            {
              icon: "document",
              name: "Agent rapprochement",
              desc: "Rapprochez les flux et signalez les anomalies.",
            },
            {
              icon: "support",
              name: "Agent ops client",
              desc: "Traitez les demandes clients et escalades métier.",
            },
            {
              icon: "property",
              name: "Agent contrôles",
              desc: "Automatisez les contrôles récurrents et la piste d’audit.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "CORE BANKING" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "FINANCE APIs" },
          ],
        },
        {
          id: "retail",
          label: "RETAIL",
          title: "Force de travail IA — Retail",
          cta: "Explorer le pack Retail",
          agents: [
            {
              icon: "ops",
              name: "Agent ops catalogue",
              desc: "Maintenez et enrichissez le catalogue produit.",
            },
            {
              icon: "support",
              name: "Agent support N1",
              desc: "Répondez aux clients et routez les escalades.",
            },
            {
              icon: "reporting",
              name: "Agent signaux de demande",
              desc: "Détectez les signaux de demande et d’assortiment.",
            },
            {
              icon: "lead",
              name: "Agent leads & fidélité",
              desc: "Qualifiez les leads et animez la fidélisation.",
            },
            {
              icon: "document",
              name: "Agent contenus merch",
              desc: "Produisez fiches produit et contenus merchandising.",
            },
            {
              icon: "property",
              name: "Agent assistance stock",
              desc: "Suivez stock, ruptures et priorités d’approvisionnement.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "ERP" },
            { icon: "folder", label: "PIM" },
            { icon: "cloud", label: "RETAIL APIs" },
          ],
        },
        {
          id: "industry",
          label: "INDUSTRIE",
          title: "Force de travail IA — Industrie",
          cta: "Explorer le pack Industrie",
          agents: [
            {
              icon: "ops",
              name: "Agent préparation maintenance",
              desc: "Préparez interventions et dossiers de maintenance.",
            },
            {
              icon: "reporting",
              name: "Agent contrôle qualité",
              desc: "Contrôlez la qualité et documentez les non-conformités.",
            },
            {
              icon: "document",
              name: "Agent reporting ops",
              desc: "Produisez les reportings opérationnels et KPI usine.",
            },
            {
              icon: "support",
              name: "Agent support d’équipe",
              desc: "Assistez les équipes de shift sur procédures et alertes.",
            },
            {
              icon: "lead",
              name: "Agent suivi fournisseurs",
              desc: "Suivez fournisseurs, délais et exceptions.",
            },
            {
              icon: "property",
              name: "Agent docs sécurité",
              desc: "Gérez procédures sécurité et documentation terrain.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "MES / ERP" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "OT APIs" },
          ],
        },
        {
          id: "services",
          label: "SERVICES PRO",
          title: "Force de travail IA — Services pro",
          cta: "Explorer le pack Services Pro",
          agents: [
            {
              icon: "ops",
              name: "Agent préparation delivery",
              desc: "Préparez livrables et jalons de mission.",
            },
            {
              icon: "document",
              name: "Agent capture de savoir",
              desc: "Capturez et structurez le savoir projet.",
            },
            {
              icon: "reporting",
              name: "Agent reporting client",
              desc: "Produisez reportings client et synthèses d’avancement.",
            },
            {
              icon: "lead",
              name: "Agent assistance propositions",
              desc: "Accélérez réponses à appels d’offres et propositions.",
            },
            {
              icon: "support",
              name: "Agent assistance staffing",
              desc: "Appuyez le staffing et le matching de compétences.",
            },
            {
              icon: "property",
              name: "Agent ops timesheets",
              desc: "Suivez temps, allocations et exceptions de facturation.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "PSA / ERP" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "SERVICE APIs" },
          ],
        },
      ],
    },
    roi: {
      eyebrow: "08 / ROI",
      titleBefore: "Une IA qui ",
      titleAccent: "se paie elle-même.",
      employees: "Employés",
      hours: "Heures de travail répétitif / semaine",
      cost: "Coût horaire moyen (€)",
      capacity: "Capacité automatisable potentielle",
      fte: "FTE",
      annual: "Valeur opérationnelle annuelle",
      note: "Estimation indicative — hypothèses ajustables. Pas de promesse de ROI fixe.",
      cta: "Discuter de vos hypothèses",
      investment: "Investissement estimé (année 1)",
      roiPct: "ROI estimé",
    },
    ops: {
      eyebrow: "09 / OPÉRATIONS IA",
      titleBefore: "Votre force de travail IA ne s’arrête pas au déploiement. ",
      titleAccent: "Nous non plus.",
      items: [
        "Supervision",
        "Mises à jour modèles et prompts",
        "Gestion d’incidents",
        "Maintenance connecteurs",
        "Correctifs sécurité",
        "Optimisation d’usage",
        "Suivi de performance",
        "Amélioration continue",
      ],
    },
    finalCta: {
      titleBefore: "L’expérimentation IA est terminée. ",
      titleAccent: "Il est temps d’opérer.",
      cta: "Démarrer avec SIGNAL",
      tagline: "Intelligence humaine. Échelle artificielle.",
    },
  },
  en: {
    hero: {
      titleBefore: "AI shouldn't be ",
      titleAccent: "another tool.",
      titleAfter: " It should transform how your company operates.",
      sub: "From strategy to execution, Remparia turns AI into a governed operating system for your business.",
      ctaPrimary: "Build your AI operating model",
      ctaSecondary: "See Remparia in action",
      badges: [
        "Sovereign-ready",
        "Model agnostic",
        "Human controlled",
        "Enterprise governed",
      ],
    },
    problem: {
      eyebrow: "02 / THE PROBLEM",
      titleBefore: "Everyone is experimenting with AI. ",
      titleAccent: "Few companies are operating with it.",
      sideLead: "The challenge",
      sideRest: "isn't accessing AI anymore. It's turning AI into an ",
      sideAccent: "operating capability.",
      today: "TODAY",
      withUs: "WITH REMPARIA",
      rows: [
        { today: "Chatbots", withUs: "AI Workers" },
        { today: "Isolated PoCs", withUs: "Connected workflows" },
        { today: "10 different tools", withUs: "One operating layer" },
        { today: "Shadow AI", withUs: "Governed AI" },
        { today: "Unclear ROI", withUs: "Measured outcomes" },
      ],
    },
    model: {
      eyebrow: "03 / OUR MODEL",
      title: "Our method. Your AI operating model.",
      steps: [
        {
          n: "01",
          tag: "SIGNAL",
          icon: "signal",
          title: "Find the value.",
          desc: "Discover, prioritize and quantify where AI can transform your operations.",
          items: ["Discover", "Score", "Prioritize", "ROI"],
        },
        {
          n: "02",
          tag: "STUDIO",
          icon: "studio",
          title: "Build the workforce.",
          desc: "Design specialized AI agents and multi-agent workflows around your business.",
          items: ["Agents", "Skills", "Workflows", "Tools"],
        },
        {
          n: "03",
          tag: "OS",
          icon: "os",
          title: "Run the system.",
          desc: "One control plane to orchestrate agents, models, tools and enterprise data.",
          items: ["Models", "Agents", "Data", "Connectors"],
        },
        {
          n: "04",
          tag: "GOVERNANCE",
          icon: "governance",
          title: "Stay in control.",
          desc: "Observe every action. Control permissions. Audit decisions. Govern AI at scale.",
          items: ["Identity", "Policies", "Audit", "Observability"],
        },
      ],
    },
    org: {
      eyebrow: "04 / SEE IT IN ACTION",
      titleBefore: "See an AI organization ",
      titleAccent: "at work.",
      body: "A mission comes in, the orchestrator delegates, agents execute, humans approve — everything logged in Remparia OS.",
      cta: "Launch interactive demo",
      logTitle: "Activity",
      logs: [
        { icon: "mission", title: "New mission received", time: "10:23:54" },
        { icon: "sales", title: "Sales Agent started", time: "10:32:13" },
        { icon: "document", title: "Document Agent called", time: "10:52:21" },
        { icon: "crm", title: "CRM tool used", time: "10:57:27" },
        { icon: "human", title: "Human approval", time: "11:03:02" },
        { icon: "done", title: "Task completed", time: "11:06:14" },
      ],
      saved: "14 min saved",
      human: { title: "HUMAN", desc: "Approves / Validates" },
      orchestrator: { title: "ORCHESTRATOR", desc: "Plans and delegates" },
      agents: [
        { icon: "salesai", title: "SALES AI", desc: "Qualify & engage" },
        { icon: "docai", title: "DOC AI", desc: "Read & prepare" },
        { icon: "finance", title: "FINANCE AI", desc: "Analyse & control" },
      ],
      os: "REMPARIA OS",
      tools: [
        { icon: "crm", label: "CRM" },
        { icon: "erp", label: "ERP" },
        { icon: "email", label: "Email" },
        { icon: "docs", label: "Docs" },
        { icon: "apis", label: "APIs" },
      ],
    },
    workforce: {
      eyebrow: "05 / AI WORKFORCE",
      titleBefore: "Don't add another chatbot. ",
      titleAccent: "Build an AI workforce.",
      body: "Agents don't work alone. They collaborate in workflows governed by Remparia OS.",
      agents: [
        {
          tag: "RESEARCH",
          title: "Research Agent",
          desc: "Research, synthesis and sourcing under business rules.",
        },
        {
          tag: "SALES",
          title: "Sales Agent",
          desc: "Qualification, follow-up and commercial prep.",
        },
        {
          tag: "DOCUMENT",
          title: "Document Agent",
          desc: "Collection, checks and document production.",
        },
        {
          tag: "OPS",
          title: "Operations Agent",
          desc: "Recurring processes, escalations and reporting.",
        },
        {
          tag: "FINANCE",
          title: "Finance Agent",
          desc: "Controls, reconciliations and analytical prep.",
        },
        {
          tag: "CUSTOM",
          title: "Custom Agent",
          desc: "Build your own AI agent.",
          href: "/studio",
        },
      ],
    },
    sovereignty: {
      eyebrow: "06 / SOVEREIGNTY",
      titleBefore: "Your AI. Your infrastructure. ",
      titleAccent: "Your rules.",
      os: "REMPARIA OS",
      osTagline: "ORCHESTRATE. GOVERN. SCALE.",
      modes: [
        {
          id: "cloud",
          title: "Remparia Cloud",
          subtitle: "Managed by Remparia",
          badge: "Fastest",
          badgeIcon: "zap",
          attrs: [
            { label: "Deployment", value: "Managed", icon: "cloud" },
            { label: "Data residency", value: "Configurable", icon: "database" },
            { label: "Infra control", value: "Remparia", icon: "building" },
          ],
          modelsLabel: "Models",
          models: [
            { label: "Mistral", icon: "mistral" },
            { label: "Llama", icon: "llama" },
            { label: "OpenAI", icon: "openai" },
            { label: "Anthropic", icon: "anthropic" },
          ],
          base: [
            { label: "Enterprise data", icon: "database" },
            { label: "AI agents", icon: "agents" },
          ],
          tools: [
            { label: "CRM", icon: "crm" },
            { label: "ERP", icon: "erp" },
            { label: "Email", icon: "email" },
            { label: "Docs", icon: "docs" },
            { label: "APIs", icon: "apis" },
          ],
          features: [
            "Production in days",
            "Public models of your choice",
            "Fully managed operations",
          ],
          tagline: "Fastest path to production",
          taglineIcon: "zap",
        },
        {
          id: "sovereign",
          title: "Sovereign Cloud",
          subtitle: "European infrastructure",
          badge: "EU / France",
          badgeIcon: "shield",
          boundary: "Sovereign perimeter EU / France",
          attrs: [
            { label: "Deployment", value: "Sovereign environment", icon: "globe" },
            { label: "Data residency", value: "EU / France", icon: "database" },
            { label: "Infra control", value: "Dedicated", icon: "server" },
          ],
          modelsLabel: "Models",
          models: [
            { label: "Mistral", icon: "mistral" },
            { label: "Llama", icon: "llama" },
            { label: "Private LLM", icon: "private" },
          ],
          base: [
            { label: "AI agents", icon: "agents" },
            { label: "Enterprise data", icon: "database" },
          ],
          tools: [
            { label: "CRM", icon: "crm" },
            { label: "ERP", icon: "erp" },
            { label: "Email", icon: "email" },
            { label: "Docs", icon: "docs" },
            { label: "APIs", icon: "apis" },
          ],
          features: [
            "Data residency",
            "Isolated network",
            "Encryption at rest and in transit",
            "Audit logs and monitoring",
            "Sovereign compliance (GDPR, NIS2, DORA…)",
          ],
          tagline: "European infrastructure. Enterprise control.",
          taglineIcon: "shield",
        },
        {
          id: "onprem",
          title: "On-premise",
          subtitle: "Your infrastructure. Your rules.",
          badge: "Air-gap",
          badgeIcon: "lock",
          boundary: "Customer perimeter — no data leaves",
          attrs: [
            { label: "Deployment", value: "Customer infrastructure", icon: "server" },
            { label: "Data residency", value: "Customer environment", icon: "database" },
            { label: "Infra control", value: "Customer", icon: "key" },
          ],
          modelsLabel: "Private models",
          models: [
            { label: "Llama", icon: "llama" },
            { label: "Mistral", icon: "mistral" },
            { label: "Custom LLM", icon: "private" },
          ],
          base: [
            { label: "AI agents", icon: "agents" },
            { label: "Enterprise data", icon: "database" },
            { label: "Tools", icon: "tools" },
          ],
          tools: [
            { label: "ERP", icon: "erp" },
            { label: "CRM", icon: "crm" },
            { label: "DMS", icon: "folder" },
            { label: "Databases", icon: "database" },
            { label: "APIs", icon: "apis" },
          ],
          features: [
            "Private network",
            "No data leaves your environment",
            "Customer-managed keys",
            "Audit and observability",
            "Air-gapped ready*",
          ],
          tagline: "Maximum control. Zero compromise.",
          taglineIcon: "lock",
        },
      ],
      compare: {
        columns: ["Remparia Cloud", "Sovereign Cloud", "On-premise"],
        rows: [
          {
            label: "Speed to deploy",
            values: ["Fast", "Medium", "Longer"],
            icons: ["zap", "clock", "hourglass"],
          },
          {
            label: "Operations",
            values: [
              "Remparia managed",
              "Remparia + partner / customer",
              "Customer (with Remparia support)",
            ],
          },
          {
            label: "Flexibility",
            values: ["High", "Very high", "Maximum"],
          },
          {
            label: "Ideal for",
            values: [
              "Quick start, agility",
              "Regulated industries, sovereignty",
              "Sensitive environments, full control",
            ],
          },
        ],
      },
    },
    industries: {
      eyebrow: "07 / INDUSTRY SOLUTIONS",
      titleBefore: "Built for ",
      titleAccent: "your industry.",
      titleAfter: " Not from scratch.",
      body: "Choose your industry. We deploy your AI workforce.",
      orchestrator: "ORCHESTRATOR",
      osTitle: "REMPARIA OS",
      osTagline: "GOVERN. ORCHESTRATE. SCALE.",
      tabs: [
        {
          id: "real-estate",
          label: "REAL ESTATE",
          title: "Real Estate AI Workforce",
          cta: "Explore Real Estate pack",
          agents: [
            {
              icon: "lead",
              name: "Lead Qualification Agent",
              desc: "Qualify and score leads automatically from multiple sources.",
            },
            {
              icon: "property",
              name: "Property Matching Agent",
              desc: "Match the right properties to the right prospects.",
            },
            {
              icon: "document",
              name: "Document Agent",
              desc: "Extract, classify and manage real estate documents.",
            },
            {
              icon: "support",
              name: "Tenant Support Agent",
              desc: "Answer tenant inquiries and resolve issues instantly.",
            },
            {
              icon: "reporting",
              name: "Reporting Agent",
              desc: "Generate insights and reports on performance and occupancy.",
            },
            {
              icon: "ops",
              name: "Operations Agent",
              desc: "Automate operational tasks and improve efficiency.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "ERP" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "PROPERTY APIs" },
          ],
        },
        {
          id: "legal",
          label: "LEGAL",
          title: "Legal AI Workforce",
          cta: "Explore Legal pack",
          agents: [
            {
              icon: "document",
              name: "Document Review Agent",
              desc: "Review and synthesize legal files at scale.",
            },
            {
              icon: "ops",
              name: "Case Prep Agent",
              desc: "Prepare case materials and track deadlines.",
            },
            {
              icon: "reporting",
              name: "Compliance Check Agent",
              desc: "Check compliance and flag gaps early.",
            },
            {
              icon: "support",
              name: "Client Intake Agent",
              desc: "Qualify inbound requests and route matters.",
            },
            {
              icon: "lead",
              name: "Research Agent",
              desc: "Research case law and sources under business rules.",
            },
            {
              icon: "property",
              name: "Contract Draft Agent",
              desc: "Prepare draft contracts and standard clauses.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "DMS" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "LEGAL APIs" },
          ],
        },
        {
          id: "finance",
          label: "FINANCIAL SERVICES",
          title: "Financial Services AI Workforce",
          cta: "Explore Finance pack",
          agents: [
            {
              icon: "lead",
              name: "KYC Assist Agent",
              desc: "Accelerate KYC and document collection.",
            },
            {
              icon: "reporting",
              name: "Reporting Agent",
              desc: "Produce regulatory and analytical reporting.",
            },
            {
              icon: "ops",
              name: "Risk Prep Agent",
              desc: "Prepare risk controls and alert dossiers.",
            },
            {
              icon: "document",
              name: "Reconciliation Agent",
              desc: "Reconcile flows and flag anomalies.",
            },
            {
              icon: "support",
              name: "Client Ops Agent",
              desc: "Handle client requests and business escalations.",
            },
            {
              icon: "property",
              name: "Controls Agent",
              desc: "Automate recurring controls and audit trails.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "CORE BANKING" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "FINANCE APIs" },
          ],
        },
        {
          id: "retail",
          label: "RETAIL",
          title: "Retail AI Workforce",
          cta: "Explore Retail pack",
          agents: [
            {
              icon: "ops",
              name: "Catalog Ops Agent",
              desc: "Maintain and enrich the product catalog.",
            },
            {
              icon: "support",
              name: "Support L1 Agent",
              desc: "Answer customers and route escalations.",
            },
            {
              icon: "reporting",
              name: "Demand Signals Agent",
              desc: "Detect demand and assortment signals.",
            },
            {
              icon: "lead",
              name: "Lead & Loyalty Agent",
              desc: "Qualify leads and activate loyalty programs.",
            },
            {
              icon: "document",
              name: "Merch Content Agent",
              desc: "Produce product sheets and merchandising content.",
            },
            {
              icon: "property",
              name: "Inventory Assist Agent",
              desc: "Track stock, shortages and replenishment priorities.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "ERP" },
            { icon: "folder", label: "PIM" },
            { icon: "cloud", label: "RETAIL APIs" },
          ],
        },
        {
          id: "industry",
          label: "INDUSTRY",
          title: "Industry AI Workforce",
          cta: "Explore Industry pack",
          agents: [
            {
              icon: "ops",
              name: "Maintenance Prep Agent",
              desc: "Prepare interventions and maintenance dossiers.",
            },
            {
              icon: "reporting",
              name: "Quality Check Agent",
              desc: "Check quality and document non-conformities.",
            },
            {
              icon: "document",
              name: "Ops Reporting Agent",
              desc: "Produce operational reporting and plant KPIs.",
            },
            {
              icon: "support",
              name: "Shift Support Agent",
              desc: "Support shift teams on procedures and alerts.",
            },
            {
              icon: "lead",
              name: "Supplier Follow-up Agent",
              desc: "Follow suppliers, lead times and exceptions.",
            },
            {
              icon: "property",
              name: "Safety Docs Agent",
              desc: "Manage safety procedures and field documentation.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "MES / ERP" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "OT APIs" },
          ],
        },
        {
          id: "services",
          label: "PROFESSIONAL SERVICES",
          title: "Professional Services AI Workforce",
          cta: "Explore Professional Services pack",
          agents: [
            {
              icon: "ops",
              name: "Delivery Prep Agent",
              desc: "Prepare deliverables and mission milestones.",
            },
            {
              icon: "document",
              name: "Knowledge Capture Agent",
              desc: "Capture and structure project knowledge.",
            },
            {
              icon: "reporting",
              name: "Client Reporting Agent",
              desc: "Produce client reporting and progress briefs.",
            },
            {
              icon: "lead",
              name: "Proposal Assist Agent",
              desc: "Accelerate RFP responses and proposals.",
            },
            {
              icon: "support",
              name: "Staffing Assist Agent",
              desc: "Support staffing and skills matching.",
            },
            {
              icon: "property",
              name: "Timesheet Ops Agent",
              desc: "Track time, allocations and billing exceptions.",
            },
          ],
          tools: [
            { icon: "crm", label: "CRM" },
            { icon: "email", label: "EMAIL" },
            { icon: "erp", label: "PSA / ERP" },
            { icon: "folder", label: "DOCUMENTS" },
            { icon: "cloud", label: "SERVICE APIs" },
          ],
        },
      ],
    },
    roi: {
      eyebrow: "08 / ROI",
      titleBefore: "AI that ",
      titleAccent: "pays for itself.",
      employees: "Employees",
      hours: "Hours spent on repetitive work / week",
      cost: "Average hourly cost (€)",
      capacity: "Potential automated capacity",
      fte: "FTE",
      annual: "Annual operational value",
      note: "Indicative estimate — adjustable assumptions. No fixed ROI promise.",
      cta: "Discuss your assumptions",
      investment: "Estimated investment (year 1)",
      roiPct: "Estimated ROI",
    },
    ops: {
      eyebrow: "09 / AI OPERATIONS",
      titleBefore: "Your AI workforce doesn't stop after deployment. ",
      titleAccent: "Neither do we.",
      items: [
        "Monitoring",
        "Model & prompt updates",
        "Incident management",
        "Connector maintenance",
        "Security patches",
        "Usage optimization",
        "Performance monitoring",
        "Continuous improvement",
      ],
    },
    finalCta: {
      titleBefore: "AI experimentation is over. ",
      titleAccent: "It's time to operate.",
      cta: "Start with SIGNAL",
      tagline: "Human intelligence. Artificial scale.",
    },
  },
} as const;

export function homePremium(lang: Lang) {
  return HOME_PREMIUM[lang];
}
