import type { Lang } from "./content";

export const HOME_PREMIUM = {
  fr: {
    hero: {
      titleBefore: "L’IA ne doit pas être ",
      titleAccent: "un outil de plus.",
      titleAfter: " Elle doit transformer le fonctionnement de votre entreprise.",
      sub: "De la stratégie à l’exécution, Remparia fait de l’IA un système d’exploitation gouverné pour votre activité.",
      ctaPrimary: "Construire votre modèle d’exploitation IA",
      ctaSecondary: "Voir Remparia en action",
      badges: [
        "Souveraineté-ready",
        "Agnostique modèles",
        "Contrôle humain",
        "Gouvernance enterprise",
      ],
      osLabel: "REMPARIA OS",
      agents: [
        "Research Agent",
        "Document Agent",
        "Finance Agent",
        "Sales Agent",
        "Operations Agent",
      ],
    },
    problem: {
      eyebrow: "02 / LE CONSTAT",
      titleBefore: "Tout le monde expérimente l’IA. ",
      titleAccent: "Peu d’entreprises l’exploitent vraiment.",
      side: "Le défi n’est plus d’accéder à l’IA. C’est d’en faire une capacité opérationnelle.",
      today: "AUJOURD’HUI",
      withUs: "AVEC REMPARIA",
      rows: [
        { today: "Chatbots", withUs: "Travailleurs IA" },
        { today: "PoC isolés", withUs: "Workflows connectés" },
        { today: "10 outils différents", withUs: "Une couche d’exploitation" },
        { today: "Shadow AI", withUs: "IA gouvernée" },
        { today: "ROI flou", withUs: "Résultats mesurés" },
      ],
    },
    model: {
      eyebrow: "03 / NOTRE MODÈLE",
      title: "Notre méthode. Votre modèle d’exploitation IA.",
      steps: [
        {
          n: "01",
          tag: "SIGNAL",
          title: "Trouver la valeur",
          items: ["Discover", "Score", "Prioritize", "ROI"],
        },
        {
          n: "02",
          tag: "STUDIO",
          title: "Construire la force de travail",
          items: ["Agents", "Skills", "Workflows", "Tools"],
        },
        {
          n: "03",
          tag: "OS",
          title: "Faire tourner le système",
          items: ["Models", "Agents", "Data", "Connectors"],
        },
        {
          n: "04",
          tag: "GOVERNANCE",
          title: "Garder le contrôle",
          items: ["Identity", "Policies", "Audit", "Observability"],
        },
      ],
    },
    org: {
      eyebrow: "04 / EN ACTION",
      titleBefore: "Voir une organisation IA ",
      titleAccent: "au travail.",
      body: "Une mission entre, l’orchestrateur délègue, les agents exécutent, l’humain valide — le tout journalisé dans Remparia OS.",
      cta: "Lancer la démo interactive",
      logTitle: "Activity",
      logs: [
        "Nouvelle mission reçue",
        "Sales Agent démarré",
        "Document Agent prépare le dossier",
        "Validation humaine demandée",
        "14 min économisées",
      ],
      human: "HUMAIN",
      orchestrator: "ORCHESTRATEUR",
      agents: ["SALES", "DOC", "FINANCE"],
      tools: ["CRM", "ERP", "EMAIL", "DOCS", "APIs"],
    },
    workforce: {
      eyebrow: "05 / AI WORKFORCE",
      titleBefore: "N’ajoutez pas un chatbot. ",
      titleAccent: "Construisez une force de travail IA.",
      agents: [
        {
          tag: "RESEARCH",
          title: "Research Agent",
          desc: "Recherche, synthèse et sourcing sous règles métier.",
        },
        {
          tag: "SALES",
          title: "Sales Agent",
          desc: "Qualification, suivi et préparation commerciale.",
        },
        {
          tag: "DOCUMENT",
          title: "Document Agent",
          desc: "Collecte, contrôle et production documentaire.",
        },
        {
          tag: "OPS",
          title: "Operations Agent",
          desc: "Processus récurrents, escalades et reporting.",
        },
        {
          tag: "FINANCE",
          title: "Finance Agent",
          desc: "Contrôles, rapprochements et préparation analytique.",
        },
        {
          tag: "CUSTOM",
          title: "Custom Agent",
          desc: "Construisez le vôtre sur le même socle gouverné.",
        },
      ],
    },
    sovereignty: {
      eyebrow: "06 / SOUVERAINETÉ",
      titleBefore: "Votre IA. Votre infrastructure. ",
      titleAccent: "Vos règles.",
      tabs: [
        { id: "cloud", label: "REMPARIA CLOUD" },
        { id: "sovereign", label: "SOVEREIGN CLOUD" },
        { id: "onprem", label: "ON-PREMISE" },
      ],
      models: ["Mistral", "Llama", "OpenAI", "Anthropic"],
      checklist: [
        "Agnostique modèles",
        "Agnostique infrastructure",
        "Sécurité by design",
        "Les données ne quittent pas votre contrôle",
        "Souveraineté-ready dès la conception",
      ],
      os: "REMPARIA OS",
      data: "Enterprise Data",
      agents: "Agents",
    },
    industries: {
      eyebrow: "07 / SOLUTIONS MÉTIERS",
      titleBefore: "Conçu pour ",
      titleAccent: "votre industrie.",
      titleAfter: " Pas from scratch.",
      tabs: [
        {
          id: "real-estate",
          label: "IMMOBILIER",
          title: "Real Estate AI Workforce",
          agents: [
            "Lead Qualification",
            "Property Matching",
            "Tenant Support",
          ],
        },
        {
          id: "legal",
          label: "JURIDIQUE",
          title: "Legal AI Workforce",
          agents: ["Document Review", "Case Prep", "Compliance Check"],
        },
        {
          id: "finance",
          label: "SERVICES FINANCIERS",
          title: "Financial Services AI Workforce",
          agents: ["KYC Assist", "Reporting", "Risk Prep"],
        },
        {
          id: "retail",
          label: "RETAIL",
          title: "Retail AI Workforce",
          agents: ["Catalog Ops", "Support L1", "Demand Signals"],
        },
        {
          id: "industry",
          label: "INDUSTRIE",
          title: "Industry AI Workforce",
          agents: ["Maintenance Prep", "Quality Check", "Ops Reporting"],
        },
        {
          id: "services",
          label: "SERVICES PRO",
          title: "Professional Services AI Workforce",
          agents: ["Delivery Prep", "Knowledge Capture", "Client Reporting"],
        },
      ],
      tools: ["CRM", "ERP", "EMAIL", "DOCS", "APIs"],
    },
    roi: {
      eyebrow: "08 / ROI",
      titleBefore: "Une IA qui ",
      titleAccent: "se paie elle-même.",
      employees: "Employés",
      hours: "Heures de travail répétitif / semaine",
      cost: "Coût horaire moyen (€)",
      capacity: "Capacité automatisable potentielle",
      fte: "FTE",
      annual: "Valeur opérationnelle annuelle",
      note: "Estimation indicative — hypothèses ajustables. Pas de promesse de ROI fixe.",
      cta: "Discuter de vos hypothèses",
    },
    ops: {
      eyebrow: "09 / AI OPERATIONS",
      titleBefore: "Votre force de travail IA ne s’arrête pas au déploiement. ",
      titleAccent: "Nous non plus.",
      items: [
        "Monitoring",
        "Mises à jour modèles & prompts",
        "Gestion d’incidents",
        "Maintenance connecteurs",
        "Correctifs sécurité",
        "Optimisation d’usage",
        "Suivi de performance",
        "Amélioration continue",
      ],
    },
    finalCta: {
      titleBefore: "L’expérimentation IA est terminée. ",
      titleAccent: "Il est temps d’opérer.",
      cta: "Démarrer avec SIGNAL",
    },
  },
  en: {
    hero: {
      titleBefore: "AI shouldn't be ",
      titleAccent: "another tool.",
      titleAfter: " It should transform how your company operates.",
      sub: "From strategy to execution, Remparia turns AI into a governed operating system for your business.",
      ctaPrimary: "Build your AI operating model",
      ctaSecondary: "See Remparia in action",
      badges: [
        "Sovereign-ready",
        "Model agnostic",
        "Human controlled",
        "Enterprise governed",
      ],
      osLabel: "REMPARIA OS",
      agents: [
        "Research Agent",
        "Document Agent",
        "Finance Agent",
        "Sales Agent",
        "Operations Agent",
      ],
    },
    problem: {
      eyebrow: "02 / THE PROBLEM",
      titleBefore: "Everyone is experimenting with AI. ",
      titleAccent: "Few companies are operating with it.",
      side: "The challenge isn't accessing AI anymore. It's turning AI into an operating capability.",
      today: "TODAY",
      withUs: "WITH REMPARIA",
      rows: [
        { today: "Chatbots", withUs: "AI Workers" },
        { today: "Isolated PoCs", withUs: "Connected workflows" },
        { today: "10 different tools", withUs: "One operating layer" },
        { today: "Shadow AI", withUs: "Governed AI" },
        { today: "Unclear ROI", withUs: "Measured outcomes" },
      ],
    },
    model: {
      eyebrow: "03 / OUR MODEL",
      title: "Our method. Your AI operating model.",
      steps: [
        {
          n: "01",
          tag: "SIGNAL",
          title: "Find the value",
          items: ["Discover", "Score", "Prioritize", "ROI"],
        },
        {
          n: "02",
          tag: "STUDIO",
          title: "Build the workforce",
          items: ["Agents", "Skills", "Workflows", "Tools"],
        },
        {
          n: "03",
          tag: "OS",
          title: "Run the system",
          items: ["Models", "Agents", "Data", "Connectors"],
        },
        {
          n: "04",
          tag: "GOVERNANCE",
          title: "Stay in control",
          items: ["Identity", "Policies", "Audit", "Observability"],
        },
      ],
    },
    org: {
      eyebrow: "04 / SEE IT IN ACTION",
      titleBefore: "See an AI organization ",
      titleAccent: "at work.",
      body: "A mission comes in, the orchestrator delegates, agents execute, humans approve — everything logged in Remparia OS.",
      cta: "Launch interactive demo",
      logTitle: "Activity",
      logs: [
        "New mission received",
        "Sales Agent started",
        "Document Agent prepares the file",
        "Human approval requested",
        "14 min saved",
      ],
      human: "HUMAN",
      orchestrator: "ORCHESTRATOR",
      agents: ["SALES", "DOC", "FINANCE"],
      tools: ["CRM", "ERP", "EMAIL", "DOCS", "APIs"],
    },
    workforce: {
      eyebrow: "05 / AI WORKFORCE",
      titleBefore: "Don't add another chatbot. ",
      titleAccent: "Build an AI workforce.",
      agents: [
        {
          tag: "RESEARCH",
          title: "Research Agent",
          desc: "Research, synthesis and sourcing under business rules.",
        },
        {
          tag: "SALES",
          title: "Sales Agent",
          desc: "Qualification, follow-up and commercial prep.",
        },
        {
          tag: "DOCUMENT",
          title: "Document Agent",
          desc: "Collection, checks and document production.",
        },
        {
          tag: "OPS",
          title: "Operations Agent",
          desc: "Recurring processes, escalations and reporting.",
        },
        {
          tag: "FINANCE",
          title: "Finance Agent",
          desc: "Controls, reconciliations and analytical prep.",
        },
        {
          tag: "CUSTOM",
          title: "Custom Agent",
          desc: "Build your own on the same governed foundation.",
        },
      ],
    },
    sovereignty: {
      eyebrow: "06 / SOVEREIGNTY",
      titleBefore: "Your AI. Your infrastructure. ",
      titleAccent: "Your rules.",
      tabs: [
        { id: "cloud", label: "REMPARIA CLOUD" },
        { id: "sovereign", label: "SOVEREIGN CLOUD" },
        { id: "onprem", label: "ON-PREMISE" },
      ],
      models: ["Mistral", "Llama", "OpenAI", "Anthropic"],
      checklist: [
        "Model agnostic",
        "Infrastructure agnostic",
        "Fully secure",
        "Data never leaves your control",
        "Sovereign-ready by design",
      ],
      os: "REMPARIA OS",
      data: "Enterprise Data",
      agents: "Agents",
    },
    industries: {
      eyebrow: "07 / INDUSTRY SOLUTIONS",
      titleBefore: "Built for ",
      titleAccent: "your industry.",
      titleAfter: " Not from scratch.",
      tabs: [
        {
          id: "real-estate",
          label: "REAL ESTATE",
          title: "Real Estate AI Workforce",
          agents: [
            "Lead Qualification",
            "Property Matching",
            "Tenant Support",
          ],
        },
        {
          id: "legal",
          label: "LEGAL",
          title: "Legal AI Workforce",
          agents: ["Document Review", "Case Prep", "Compliance Check"],
        },
        {
          id: "finance",
          label: "FINANCIAL SERVICES",
          title: "Financial Services AI Workforce",
          agents: ["KYC Assist", "Reporting", "Risk Prep"],
        },
        {
          id: "retail",
          label: "RETAIL",
          title: "Retail AI Workforce",
          agents: ["Catalog Ops", "Support L1", "Demand Signals"],
        },
        {
          id: "industry",
          label: "INDUSTRY",
          title: "Industry AI Workforce",
          agents: ["Maintenance Prep", "Quality Check", "Ops Reporting"],
        },
        {
          id: "services",
          label: "PROFESSIONAL SERVICES",
          title: "Professional Services AI Workforce",
          agents: ["Delivery Prep", "Knowledge Capture", "Client Reporting"],
        },
      ],
      tools: ["CRM", "ERP", "EMAIL", "DOCS", "APIs"],
    },
    roi: {
      eyebrow: "08 / ROI",
      titleBefore: "AI that ",
      titleAccent: "pays for itself.",
      employees: "Employees",
      hours: "Hours spent on repetitive work / week",
      cost: "Average hourly cost (€)",
      capacity: "Potential automated capacity",
      fte: "FTE",
      annual: "Annual operational value",
      note: "Indicative estimate — adjustable assumptions. No fixed ROI promise.",
      cta: "Discuss your assumptions",
    },
    ops: {
      eyebrow: "09 / AI OPERATIONS",
      titleBefore: "Your AI workforce doesn't stop after deployment. ",
      titleAccent: "Neither do we.",
      items: [
        "Monitoring",
        "Model & prompt updates",
        "Incident management",
        "Connector maintenance",
        "Security patches",
        "Usage optimization",
        "Performance monitoring",
        "Continuous improvement",
      ],
    },
    finalCta: {
      titleBefore: "AI experimentation is over. ",
      titleAccent: "It's time to operate.",
      cta: "START WITH SIGNAL",
    },
  },
} as const;

export function homePremium(lang: Lang) {
  return HOME_PREMIUM[lang];
}
